# -*- coding: utf-8 -*-
# 该文件是ui文件

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(400, 300)
        Window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit = QtWidgets.QLineEdit(Window)
        self.lineEdit.setGeometry(QtCore.QRect(120, 50, 113, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Window)
        self.label.setGeometry(QtCore.QRect(30, 50, 81, 18))
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Window)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 81, 18))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Window)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 120, 113, 27))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Window)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 101, 20))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Window)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 160, 113, 27))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(Window)
        self.pushButton.setGeometry(QtCore.QRect(50, 220, 101, 29))
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Window)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 220, 101, 29))
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Window)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 50, 91, 29))
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(Window)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 81, 18))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(Window)
        self.comboBox.setGeometry(QtCore.QRect(120, 90, 111, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.lineEdit_2)
        self.label_3.setBuddy(self.lineEdit_3)
        self.label_4.setBuddy(self.lineEdit)

        self.retranslateUi(Window)
        self.pushButton_2.clicked.connect(Window.close)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Dialog"))
        self.label.setText(_translate("Window", "输入图片："))
        self.label_2.setText(_translate("Window", "缩放倍数："))
        self.label_3.setText(_translate("Window", "输出图片为："))
        self.pushButton.setText(_translate("Window", "OK"))
        self.pushButton_2.setText(_translate("Window", "Cancel"))
        self.pushButton_3.setText(_translate("Window", "选择文件"))
        self.label_4.setText(_translate("Window", "缩放方向："))
        self.comboBox.setItemText(0, _translate("Window", "横向"))
        self.comboBox.setItemText(1, _translate("Window", "纵向"))
